server:
  port: 9907
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/ddcherry?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: abc123
    druid:
      # 初始化时建立物理连接的个数
      initialSize: 1
      # 最小连接池数量
      minIdle: 3
      # 最大连接池数量
      maxActive: 20
      # 获取连接时最大等待时间，单位毫秒
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 30000
      # 用来检测连接是否有效的sql，要求是一个查询语句，常用select ‘x’
      validationQuery: select 'x'
      # 建议配置为true，不影响性能，并且保证安全性
      testWhileIdle: true
      # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      testOnBorrow: false
      # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。
      poolPreparedStatements: true
      # 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: config,stat,slf4j
      stat-view-servlet:
        # 启用StatViewServlet（监控页面）
        enabled: true
        # 监控页面的登录账户
        login-username: admin
        # 监控页面的登录密码
        login-password: admin
        # 是否允许清空统计数据
        reset-enable: true
mybatis-plus:
  # MyBatis Mapper 所对应的 XML 文件位置
  mapper-locations: classpath*:/cn/ddcherry/**/dao/*Dao.xml
  # MyBaits 别名包扫描路径
  typeAliasesPackage: cn.ddcherry.**.entity
  configuration:
    # 是否开启自动驼峰命名规则映射
    map-underscore-to-camel-case: true
    # 开启 Mybatis 二级缓存，默认为 true
    cache-enabled: false
logging:
  config: classpath:log/logback-dev.xml
